version: '3.9'

services:
  fx-deal-service:
    build:
      context: /Users/decag/IdeaProjects/fx-deals-warehouse
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fx_deals_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fx_deals_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"